name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  macOS:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        xcode_version:
          - "14.0.1"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v3
      - name: Show Environments
        run: |
          swift --version
          xcodebuild -version
      - name: Run Test
        run: ls
